version: '3'
services:
  web:
    build:
      context: .
      dockerfile: dockerfile.dev
    ports:
      - "3000:3000"
  tests:
    build:
      context: .
      dockerfile: dockerfile.dev
    command: ["npm", "run", "test"]

  

